[window]
opacity = 0.7
decorations = "full"  # "none" for borderless

[font]
normal.family = "Liberation Mono"
size = 22.0

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#cdd6f4"


